version: '3.9'

services:
  
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8005:8000
    env_file:
      - ./.env
    depends_on:
      - web-db

  web-db:
    image: postgres:17.2-alpine3.21
    restart: always
    env_file:
      - ./.env
    ports:
      - "6432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d